### ISSUE TITLE
azure.xml is not rendering data

### ISSUE THREAD

**Issue by ghoshasish99** [CognizantOpenSource/Cognizant-Intelligent-Test-Scripter#1]
package `package com.cognizant.cognizantits.engine.reporting.impl.azure`
class  `AzureSummaryHandler`

Sequence needs to be reversed : 
```Java
        resetAzureVars();

        FileOutputStream out = new FileOutputStream(AzureReportPath);
```

**Comment by potesupriya** [comment]
package package com.cognizant.cognizantits.engine.reporting.impl.azure
class AzureSummaryHandler

Sequence reversed :

FileOutputStream out = new FileOutputStream(AzureReportPath);

resetAzureVars();
